#!bin/bash
Maintenant=$(date '+%d %B %Y')

echo "Bonjour $USER. Nous sommes actuellement le $Maintenant. Bienvenu(e) dans mon projet."

read -p "Quel répertoire vous intéresse aujourd'hui ?" repo
cd "$repo" && pwd

echo "Les fichiers modifiés depuis moins d'une semaine sont :"
find  -type f -mtime -7

